// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fexpsqixtosrnukbbpqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZleHBzcWl4dG9zcm51a2JicHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjkzNDYsImV4cCI6MjA3MjAwNTM0Nn0.SR6uFTOYent1bvRmOYJz6BITyKEHv-oCLH5WRuizvec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});